name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    if: github.repository == 'Qilletni/qpm-backend'
    steps:
      - uses: actions/checkout@v6

      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v2
        with:
          changelog_file: CHANGELOG.md
          release_notes_file: RELEASE_NOTES.md
          prerelease: false

      - name: Create final release
        run: gh release create "${{ github.ref_name }}" --notes-file RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
